title:             SheroChingå¸Œç½—
email:             your-email@example.com
description:       æ¬¢è¿è®¿é—®å¸Œç½— ğŸ‘ğŸ‘ğŸ‘
author:            Kiki
baseurl:           "/"
url:               "https://www.shero-china.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   shero-ching
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
